Repository sbt/librarymanagement, pull requests merged in 2018-10, with the labels that each got.

#265 Scripted integration test infrastructure with Sbt
  .gitignore
  .travis.yml
  build.sbt
  project/SbtScriptedIT.scala
  scripted-test/src/sbt-test/lmScriptedTest/simple/Main.scala
  scripted-test/src/sbt-test/lmScriptedTest/simple/build.sbt
  scripted-test/src/sbt-test/lmScriptedTest/simple/test
Labels: review

#268 Fix the contains issue
  core/src/main/scala/sbt/librarymanagement/EvictionWarning.scala
  ivy/src/main/scala/sbt/internal/librarymanagement/IvyActions.scala
  ivy/src/main/scala/sbt/internal/librarymanagement/IvyRetrieve.scala
  ivy/src/main/scala/sbt/internal/librarymanagement/IvyScalaUtil.scala
  ivy/src/main/scala/sbt/internal/librarymanagement/MakePom.scala
  ivy/src/main/scala/sbt/internal/librarymanagement/ivyint/CachedResolutionResolveEngine.scala
  project/plugins.sbt
Labels: in progress

#269 [1.2.x] Fix the contains issue
  core/src/main/scala/sbt/librarymanagement/EvictionWarning.scala
  ivy/src/main/scala/sbt/internal/librarymanagement/IvyActions.scala
  ivy/src/main/scala/sbt/internal/librarymanagement/IvyRetrieve.scala
  ivy/src/main/scala/sbt/internal/librarymanagement/IvyScalaUtil.scala
  ivy/src/main/scala/sbt/internal/librarymanagement/MakePom.scala
  ivy/src/main/scala/sbt/internal/librarymanagement/ivyint/CachedResolutionResolveEngine.scala
Labels: in progress

#271 Update scaladoc for SemanticVersionSelector
  core/src/main/contraband-scala/sbt/librarymanagement/SemanticSelector.scala
  core/src/main/contraband/librarymanagement2.json
Labels: ready

#272 Collapse eviction warnings
  core/src/main/scala/sbt/librarymanagement/EvictionWarning.scala
  ivy/src/test/scala/sbt/internal/librarymanagement/EvictionWarningSpec.scala
Labels: in progress

#273 Collapse eviction warnings
  core/src/main/scala/sbt/librarymanagement/EvictionWarning.scala
  ivy/src/test/scala/sbt/internal/librarymanagement/EvictionWarningSpec.scala
Labels: in progress

#277 Bump IO and Util
  build.sbt
  project/Dependencies.scala
  project/build.properties
Labels: in progress
